app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Index:index }

app_cuisine:
    path:     /cuisine/{id}/{page}
    defaults: { _controller: AppBundle:Index:cuisine, page: 1 }
    requirements:
        id: \d+
        page: \d+
    
app_category:
    path:     /category/{id}/{page}
    defaults: { _controller: AppBundle:Index:category, page: 1 }
    requirements:
        id: \d+
        page: \d+
    
#cart routes
cart_add:
    path:     /cart/add/{id}
    defaults: { _controller: AppBundle:Cart:add }
    requirements:
        id: \d+

cart_remove:
    path:     /cart/remove/{id}
    defaults: { _controller: AppBundle:Cart:remove }
    requirements:
        id: \d+

cart_remove_all:
    path:     /cart/remove-all/{id}
    defaults: { _controller: AppBundle:Cart:removeAll }
    requirements:
        id: \d+
        
cart_show:
    path:     /cart/show
    defaults: { _controller: AppBundle:Cart:show }

#order routes
order_show:
    path:     /order/show
    defaults: { _controller: AppBundle:Order:show }

order_submit:
    path:     /order/submit
    defaults: { _controller: AppBundle:Order:submit }
    
#profile
profile_address:
    path:     /profile/address
    defaults: { _controller: AppBundle:Profile:address }
    
profile_address_add:
    path:     /profile/address-add
    defaults: { _controller: AppBundle:Profile:addressAdd }
    
profile_address_edit:
    path:     /profile/address-edit/{id}
    defaults: { _controller: AppBundle:Profile:addressEdit }
    requirements:
        id: \d+

profile_address_remove:
    path:     /profile/address-remove/{id}
    defaults: { _controller: AppBundle:Profile:addressRemove }
    requirements:
        id: \d+

profile_orders:
    path:     /profile/orders
    defaults: { _controller: AppBundle:Profile:orders }