app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Index:index }

app_cuisine:
    path:     /cuisine/{id}/{page}
    defaults: { _controller: AppBundle:Index:cuisine, page: 1 }
    
app_category:
    path:     /category/{id}/{page}
    defaults: { _controller: AppBundle:Index:category, page: 1 }