parameters:
    cart_factory: '\Dart\AppBunde\Service\Cart'
    min: 500
    penalty: 250
    cart_name: 'panda-cart'
    cart_item_factory_class: '\Dart\AppBundle\Factory\CartItem'
    
services:
#    app.example:
#        class: Dart\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    cart:
        class: Dart\AppBundle\Service\Cart
        arguments: [%min%, %penalty%]
    cart.manager:
        class: Dart\AppBundle\Service\CartManager
        arguments: [%cart_factory%, %cart_name%, @session, %cart_item_factory_class%]
    cart.item:
        class: Dart\AppBundle\Service\CartItem
        arguments: []
    preview:
        class: Dart\AppBundle\Service\Preview
        arguments:
            - @templating
            - @cart.manager
            - "AppBundle:Misc:cart_preview.html.twig"
    order:
        class: Dart\AppBundle\Service\OrderService
        arguments: [@order.item]
    order.item:
        class: Dart\AppBundle\Service\OrderItem
        arguments: []
    order_manager:
        class: Dart\AppBundle\Service\OrderManager
        arguments:
            - @cart.manager
            - @order
            - @order.externals
    order.externals:
        class: Dart\AppBundle\Service\OrderExternals
        arguments:
            - [@actions.delivery]
    actions.delivery:
        class: Dart\AppBundle\Service\DeliveryAction
        arguments:
            - %order_actions_delivery_min%
            - %order_actions_delivery_cost%
#fos_forms overrides
    fos_forms.user_register:
        class: Dart\AppBundle\Form\Type\RegistrationType
        arguments: []
        tags:
            - { name: form.type, alias: app_user_registration }
    app.locale_listener:
        class: Dart\AppBundle\EventListener\LocaleListener
        arguments: [%kernel.default_locale%]
        tags:
            - { name: kernel.event_subscriber }