services:
#    app.example:
#        class: Dart\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    cart:
        class: Dart\AppBundle\Service\CartService
        arguments: [@session, @cart.item]
    cart.item:
        class: Dart\AppBundle\Service\ItemService
        arguments: []
    preview:
        class: Dart\AppBundle\Service\Preview
        arguments:
            - @templating
            - @cart
            - "AppBundle::cart_preview.html.twig"
    order:
        class: Dart\AppBundle\Service\OrderService
        arguments: [@doctrine.orm.entity_manager, @cart]
#fos_forms overrides
    fos_forms.user_register:
        class: Dart\AppBundle\Form\Type\RegistrationType
        arguments: []
        tags:
            - { name: form.type, alias: app_user_registration }