services:
#    app.example:
#        class: Dart\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    cart:
        class: Dart\AppBundle\Service\CartService
        arguments: [@session, @cart.item]
    cart.item:
        class: Dart\AppBundle\Service\ItemService
        arguments: []
        