Dart\AppBundle\Entity\Cuisine:
    type: entity
    table: cuisines
    repositoryClass: Dart\AppBundle\Entity\CuisineRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 256
            options:
                comment: "Cuisine name"
    oneToMany:
        categories:
            targetEntity: Category
            mappedBy: cuisine