Dart\AppBundle\Entity\DeliveryAddress:
    type: entity
    table: delivery_addresses
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        order_id:
            type: integer
            nullable: false
            options:
                comment: "Id of order this delivery address attached to"
        street:
            type: string
            length: 256
            nullable: false
            options:
                comment: "Delivery street"
        building:
            type: string
            length: 256
            nullable: true
            options:
                comment: "Delivery building"
        porch:
            type: integer
            nullable: true
            options:
                comment: "Delivery porch"
        apartment:
            type: integer
            nullable: true
            options:
                comment: "Delivery apartment"
        intercome_code:
            type: string
            length: 256
            nullable: true
            options:
                comment: "Intercome code"
        note:
            type: text
            nullable: true
            options:
                comment: "Additional notes, like street some special markers etc."
    oneToOne:
        order:
            targetEntity: Order
            inversedBy: delivery_address
            joinColumn:
                name: order_id
                referencedColumnName: id
            