Dart\AppBundle\Entity\Meal:
    type: entity
    table: meals
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        category_id:
            type: integer
            nullable: false
            options:
                comment: "Meal cuisine"
        name:
            type: string
            length: 256
            nullable: false
            options:
                comment: "Meal name"
        description:
            type: text
            nullable: true
            options:
                comment: "Meal description"
        price:
            type: integer
            nullable: false
            options:
                comment: "Meal price"
        weight:
            type: integer
            nullable: false
            options:
                comment: "Meal weight"
        image:
            type: string
            length: 256
            nullable: false
            options:
                comment: "Meal image"
        creation_date:
            type: datetime
            nullable: false
            options:
                comment: "Meal creation date/time"
        modification_date:
            type: datetime
            nullable: false
            options:
                comment: "Meal last modification date/time"
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: meals
            joinColumn:
                name: category_id
                referencedColumnName: id
    oneToMany:
        order_products:
            targetEntity: OrderItem
            mappedBy: product
    lifecycleCallbacks:
        prePersist: [setCreationDate, setModificationDate, imageUpload]
        preUpdate: [imageUpload]