Dart\AppBundle\Entity\OrderItem:
    type: entity
    table: order_items
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        order_id:
            type: integer
            nullable: false
            options:
                comment: "id of order this item attached to"
        product_id:
            type: integer
            nullable: false
            options:
                comment: "Id of original product ordered"
        count:
            type: integer
            nullable: false
            options:
                comment: "Count of product units ordered"
    manyToOne:
        order:
            targetEntity: Order
            inversedBy: order_items
            joinColumn:
                name: order_id
                referencedColumnName: id
        product:
            targetEntity: Meal
            inversedBy: order_products
            joinColumn:
                name: product_id
                referencedColumnName: id
        