Dart\AppBundle\Entity\OrderUserProfile:
    type: entity
    table: order_user_profiles
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        order_id:
            type: integer
            nullable: false
            options:
                comment: "Id of order this profile attached to"
        name:
            type: string
            length: 256
            nullable: false
            options:
                comment: "Client name"
        phone:
            type: string
            length: 256
            nullable: false
            options:
                comment: "Client phone"
    oneToOne:
        order:
            targetEntity: Order
            inversedBy: order_user_profile
            joinColumn:
                name: order_id
                referencedColumnName: id