Dart\AppBundle\Entity\UserProfile:
    type: entity
    table: user_profiles
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 256
            nullable: false
            options:
                comment: "Name of user who made an order"
        phone:
            type: string
            length: 256
            nullable: false
            options:
                comment: "Phone number of user who made an order"
    oneToOne:
        user:
            targetEntity: User
            mappedBy: profile