Dart\AppBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        creation_date:
            type: datetime
            nullable: false
            options:
                comment: "User creation date/time"
        modification_date:
            type: datetime
            nullable: false
            options:
                comment: "User info update date/time"
    oneToOne:
        profile:
            targetEntity: UserProfile
            mappedBy: user
    oneToMany:
        addresses:
            targetEntity: UserAddress
            mappedBy: user
    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
                
    lifecycleCallbacks:
        prePersist: [prePersist]