admin_homepage:
    path:     /admin/index
    defaults: { _controller: AdminBundle:Index:index }

admin_order_create:
    path:     /admin/order/create
    defaults: { _controller: AdminBundle:Order:create }
    requirements:
        method: post