services:
    admin.user:
        class: Dart\AdminBundle\Admin\UserAdmin
        arguments: [~, Dart\AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Users }
    admin.meal:
        class: Dart\AdminBundle\Admin\MealAdmin
        arguments: [~, Dart\AppBundle\Entity\Meal, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Meals }
        calls:
            - [ setTemplate, [edit, AdminBundle:SonataAdmin:Meal/edit.html.twig]]
    admin.cuisine:
        class: Dart\AdminBundle\Admin\CuisineAdmin
        arguments: [~, Dart\AppBundle\Entity\Cuisine, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Cuisines }
    admin.category:
        class: Dart\AdminBundle\Admin\CategoryAdmin
        arguments: [~, Dart\AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
    admin.order:
        class: Dart\AdminBundle\Admin\OrderAdmin
        arguments: [~, Dart\AppBundle\Entity\Order, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Order }